### ISSUE TITLE
引入工具在微信小程序端报错

### ISSUE THREAD

**Issue by robin901118** [cgxqd/utilscore#1]
`import {deepClone} from 'utilscore/dist/index';`

在微信小程序端报错，报错内容：
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'name' of undefined 
 TypeError: Cannot read property 'name' of undefined

**Comment by cgxqd** [comment]
由于将原型文件引入打包文件，导致这个模块引入bug，已解决，衷心感谢issue。
