### ISSUE TITLE
不兼容IE 10 11浏览器

### ISSUE THREAD

**Issue by zengjingke** [cgxqd/utilscore#3]
不兼容IE 10 11浏览器

**Comment by cgxqd** [comment]
如果你的目标浏览器不原生支持 es6+的某些语法(IE：你们都看我干嘛)，你得自己提供 polyfill。

**Comment by zengjingke** [comment]
好吧

**Comment by zengjingke** [comment]
vue.config.js配置了transpileDependencies: ["utilscore"]后import { mask } from "utilscore";

会出现"export 'mask' was not found in 'utilscore'的错误

**Comment by cgxqd** [comment]
utilscore 不用加入到transpileDependencies中。
